title: Segmentation fault at 0x0584
email: archid-@student.1337.ma
baseurl: /
description: This is my personal blog, I shall be updating it often.
url: 0x0584.github.io
domain: 0x0584.github.io
twitter_username: 0x0584
github_username:  0x0584

# Build settings
theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
