title: "Segmentation fault at 0x0584"
email: "rchid.anas@hotmail.com"
description: "This is my personal blog."
baseurl: "" 
url: "http://0x0584.github.com" 
twitter_username: "0x0584"
github_username:  "0x0584"

# Build settings
markdown: kramdown
usemathjax: true
theme: minima
plugins:
  - jekyll-feed
