title: "Segmentation fault at 0x0584"
email: "archid-@student.1337.ma"
description: "This is my personal blog, I shall be updating it regularly."
baseurl: "" 
url: "http://0x0584.github.com" 
twitter_username: "0x0584"
github_username:  "0x0584"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
